services:
  - type: web
    name: trytry
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn_config.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--worker-tmp-dir /dev/shm --workers=4 --threads=2 --worker-class=gthread"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
